services:
  gitea-db:
    restart: unless-stopped
    image: postgres:13
    container_name: gitea-db
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_pass
    volumes:
      - gitea-db-data:/var/lib/postgresql/data
    networks:
      - gitea-net
    dns:
      - 10.80.0.2
    
  gitea:
    restart: unless-stopped
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea_pass
      - GITEA__security__DISABLE_WEBHOOKS=false
      - GITEA__webhook__ALLOWED_HOST_LIST=*.lan
      - GITEA__webhook__DELIVER_TIMEOUT=30
      # - GITEA__cron__ENABLED=true
    volumes:
      - gitea-data:/data
    ports:
      - 3000:3000
      - 3022:22
    depends_on:
      - gitea-db
    networks:
      - gitea-net
    dns:
      - 10.80.0.2
    healthcheck:
      test: curl -sS http://127.0.0.1:3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  
  gitea-runner:
    depends_on:
      - gitea
    restart: unless-stopped
    container_name: gitea-runner
    image: gitea/act_runner:latest
    environment:
      - CONFIG_FILE=/config/runner.yaml
      - GITEA_INSTANCE_URL=http://gitea.lan
      - GITEA_RUNNER_REGISTRATION_TOKEN
      - GITEA_RUNNER_NAME=runner
      # - GITEA_RUNNER_LABELS="${RUNNER_LABELS}"
    volumes:
      - ./config:/config
      - gitea-runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      10.80.0.2

networks:
  gitea-net:

volumes:
  gitea-db-data:
  gitea-data:
  gitea-runner-data:

